name: CI

on:
  workflow_run:
    workflows: ["Build", "Test"]
    branches: [twofu]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: yarn test

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: yarn deploy
