name: CI 

on:
  push:
    branches: [ twofu ]
  pull_request:
    branches: [ twofu ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: yarn test
